sudo: required
services:
  - docker

before_install:
  - docker run --name mongo_eve -d mongo:latest
  - docker build -t crazygoatstudio/apigator .
  - docker run -d -p 0.0.0.0:5000:5000 --name travis-eve --link mongo_eve:mongo crazygoatstudio/apigator
  - docker ps -a
  - sleep 5

script:
#  - bundle exec rake test
  - curl -i http://localhost:5000/?pretty
  - curl -i http://localhost:5000/lists?pretty

after_script:
 - docker stop travis-eve
 - docker rm travis-eve